### ISSUE TITLE
Sample config file  to set up local development is missing.

### ISSUE THREAD

**Issue by ianmuhia** [kwandapchumba/cloud-bookmark-manager#2]

**Comment by haron1996** [comment]
accessTokenDuration=
dbString=postgresql://{user}t:{password}@localhost:5432/{database}?sslmode=disable
doSecret=
doSpaces=
mailJetApiKey=
mailJetSecretKey=
mailgunApiKey=
mailgunDomain=
publicKeyHex=
refreshTokenDuration=
secretKeyHex=
